### ISSUE TITLE
hostname needs to be lowercased for use in object account

### ISSUE THREAD

**Issue by jbens-pstg** [joshuarobinson/flashblade-plumbing#3]
Log error: {"jsonrpc": "2.0", "error": {"message": "Account name must be between 3 and 63 characters (lower case letter, number and '-') in length and begin and end with a lower case letter or number. The name cannot contain two consecutive '-' and cannot be a 12 digit number.", "code": -32602}, "id": "35484852"}

Turns out hostname was uppercase and so account name had uppercase in it.

**Comment by joshuarobinson** [comment]
Hi Johny,
the commit here https://github.com/joshuarobinson/flashblade-plumbing/commit/1b52f8e84e6daa82c4d1536d9d3aaa5741a6f003

was supposed to have fixed this issue. Can you confirm that you're using a new enough version (0.4) to include that fix?

**Comment by jbens-pstg** [comment]
Ah right, yeah, our friends are still using the 3.x version :-(
Tested 0.4 in the lab and it works even with uppercase in the hostname.
Sorry!
