### ISSUE TITLE
On multi-homed hosts a slow connection may be used

### ISSUE THREAD

**Issue by jbens-pstg** [joshuarobinson/flashblade-plumbing#4]
Multiple nics and using a slow connection (host management network) for the first run:

Found 2 subnets with data VIPs. Will test one VIP per subnet.
Checking for filesystem deleteme-go-plumbing-init231c-idf-18
Found 1 data VIPs in subnet net2, will use: 10.52.6.12
Mounting NFS export /deleteme-go-plumbing-init231c-idf-18 at 10.52.6.12
Running NFS write test.
Write Throughput = 118.2 MB/s
Running NFS read test.
Read Throughput = 117.3 MB/s
Found 1 data VIPs in subnet net3, will use: 10.52.8.16
Mounting NFS export /deleteme-go-plumbing-init231c-idf-18 at 10.52.8.16
Running NFS write test.
Write Throughput = 1.3 GB/s
Running NFS read test.
Read Throughput = 3.1 GB/s

**Comment by joshuarobinson** [comment]
Working as expected :)

Note that the test is time-based, so if you want to run through quicker, you can use the "-duration" flag set to something less than the default of 60s
